pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {
        stage('Get Source Code from GitHub') {
            steps {
                git branch: 'master', url: 'https://github.com/MineOBrine/simple-java-maven-app.git'
            }
        }

        stage('Build Project') {
            steps {
                bat 'mvn clean verify'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    bat 'mvn sonar:sonar -Dsonar.projectKey=sample-java-app'
                }
            }
        }
    }
}
